### PR TITLE
Use URL to retrieve the repo gpgkey

### LINKED ISSUE #43: EPEL GPG key not found on rhel/ubi8
Using `geerlingguy/docker-ubi8-ansible:latest` I am getting:

```
    TASK [geerlingguy.repo-epel : Check if EPEL repo is already configured.] *******
    Thursday 24 September 2020  11:07:41 +0200 (0:00:04.626)       0:00:15.583 ****
    ok: [rhel8]

    TASK [geerlingguy.repo-epel : Import EPEL GPG key.] ****************************
    Thursday 24 September 2020  11:07:45 +0200 (0:00:04.745)       0:00:20.329 ****
fatal: [rhel8]: FAILED! => changed=false
  msg: Not a valid key /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
```

```
[root@rhel8 /]# ls /etc/pki/rpm-gpg/
RPM-GPG-KEY-redhat-beta  RPM-GPG-KEY-redhat-release
```

It would looks like the EPEL key is only available by default on Centos and not rhel/ubi ?

### PR DESCRIPTION
**Pull request by cognifloyd**
Fixes #43

Also, this uses the fingerprint parameter which was introduced in
ansible 2.9. So, a version comparison is needed to exclude that
parameter if running on an older ansible version. The version test was
renamed to version in ansible 2.5, so bump minimum ansible version as
well.

### CODE REVIEW

**Comment by triwats** [comment]
Looks good to me @cognifloyd - the only feedback I might have is to move the `when` to the end of the block to ensure that it's uniform with the rest of the code.

Out of interested, do we know how regularly these fingerprints change? And is there any release lifecycle documentation around it since we're including them hardcoded in the module?

**Comment by cognifloyd** [comment]
K. I adjusted the location of `when` and added the retry safety since downloading the key could have intermittent network errors.

Also, changing the gpg key is afaik an unheard of thing to do. Every package in a given repo is signed with that key, so if the key were changed every rpm would have to be resigned. So, it would take something extreme to require changing that key.
iow: It should be safe to hard-code the fingerprints.

**Comment by geerlingguy** [comment]
@cognifloyd - As someone who has seen keys change with some frequency (at least once every 5-10 years) causing a fun amount of havoc, I'd rather not hardcode the fingerprint into my role—it also requires at least 2.9 for that feature, which is fine, but I'd rather not add the complexity and would rather just improve things using the 2.5+ method.

**Comment by geerlingguy** [comment]
I merged this PR but reverted the fingerprinting (at least for now), as this fixes a bug that occurs on RHEL (which I can't test in CI like I can with CentOS). I might consider the fingerprinting, but that would need to be a separate feature request/reasoning added in a separate issue or PR.

**Pull request merged**
